<?php
// PHP Variables & metadata
$currentChapterTitle = 'The nature of a scientific theory';
$currentChapterDescription = 'In order to talk about the nature of the universe and to discuss such questions as whether it has a beginning or an end, you have to be clear about what a scientific theory is.';
$nextChapterTitle = 'Newtons Universe';
$nextChapterURL = '4';
?>

<?php include '../parts/header.php';?>

  <div class="three book">
    <div class="container">
      <section class="chapter">
        <h2 id="chapter-3">The nature of a scientific theory</h2>

        <p>In order to talk about the nature of the universe and to discuss such questions as whether it has a beginning or an end, you have to be clear about what a scientific theory is. We shall take the simpleminded view that a theory is just a model of the universe, or a restricted part of it, and a set of rules that relate quantities in the model to observations that we make. It exists only in our minds and does not have any other reality (whatever that might mean). A theory is a good theory if it satisfies two requirements. It must accurately describe a large class of observations on the basis of a model that contains only a few arbitrary elements, and it must make definite predictions about the results of future observations. For example, Aristotle believed Empedocles’s theory that everything was made out of four elements: earth, air, fire, and water. This was simple enough but did not make any definite predictions. On the other hand, Newton’s theory of gravity was based on an even simpler model, in which bodies attracted each other with a force that was <a href="/glossary#proportional" class="one-digit footnote-marker" rel="footnote">proportional</a> to a quantity called their <a href="/glossary#mass" class="one-digit footnote-marker" rel="footnote">mass</a> and inversely proportional to the square of the distance between them. Yet it predicts the motions of the sun, the moon, and the planets to a high degree of accuracy. </p>


        <p>Any physical theory is always provisional, in the sense that it is only a hypothesis: you can never prove it. No matter how many times the results of experiments agree with some theory, you can never be sure that the next time a result will not contradict the theory. On the other hand, you can disprove a theory by finding even a single observation that disagrees with the predictions of the theory. As philosopher of science Karl Popper has emphasized, a good theory is characterized by the fact that it makes a number of predictions that could in principle be disproved or falsified by observation. Each time new experiments are observed to agree with the predictions, the theory survives and our confidence in it is increased; but if ever a new observation is found to disagree, we have to abandon or modify the theory.</p>


        <p>At least that is what is supposed to happen, but you can always question the competence of the person who carried out the observation.</p>

        <p>In practice, what often happens is that a new theory is devised that is really an extension of the previous theory. For example, very accurate observations of the planet Mercury revealed a small difference between its motion and the predictions of Newton’s theory of gravity. <a href="albert-einstein" data-media="(min-width: 50em)" data-replace="snippet-einstein.html"  data-target="#einstein">Einstein’s</a> general theory of relativity predicted a slightly different motion than Newton’s theory did. The fact that Einstein’s predictions matched what was seen, while Newton’s did not, was one of the crucial confirmations of the new theory. However, we still use Newton’s theory for most practical purposes because the difference between its predictions and those of <a href="/glossary#general-relativity" class="one-digit footnote-marker" rel="footnote">general relativity</a> is very small in the situations that we normally deal with. (Newton’s theory also has the great advantage that it is much simpler to work with than Einstein’s!)</p>

        <div id="einstein" class="person einstein"></div>

        <p>The eventual goal of science is to provide a single theory that describes the whole universe. However, the approach most scientists actually follow is to separate the problem into two parts. First, there are the laws that tell us how the universe changes with time. (If we know what the universe is like at any one time, these physical laws tell us how it will look at any later time.) Second, there is the question of the initial state of the universe. Some people feel that science should be concerned with only the first part; they regard the question of the initial situation as a matter for metaphysics or religion. They would say that God, being omnipotent, could have started the universe off any way He wanted. That may be so, but in that case God also could have made it develop in a completely arbitrary way. Yet it appears that God chose to make it evolve in a very regular way, according to certain laws. It therefore seems equally reasonable to suppose that there are also laws governing the initial state.</p>


        <p>It turns out to be very difficult to devise a theory to describe the universe all in one go. Instead, we break the problem up into bits and invent a number of partial theories. Each of these partial theories describes and predicts a certain limited class of observations, neglecting the effects of other quantities, or representing them by simple sets of numbers. It may be that this approach is completely wrong. If everything in the universe depends on everything else in a fundamental way, it might be impossible to get close to a full solution by investigating parts of the problem in isolation. Nevertheless, it is certainly the way that we have made progress in the past. The classic example is again the Newtonian theory of gravity, which tells us that the gravitational force between two bodies depends only on one number associated with each body, its mass, and is otherwise independent of what the bodies are made of. Thus we do not need to have a theory of the structure and constitution of the sun and the planets in order to calculate their orbits.</p>

        <p>Today scientists describe the universe in terms of two basic partial theories—the general theory of relativity and <a href="/glossary#quantum-mechanics" class="one-digit footnote-marker" rel="footnote">quantum mechanics</a>. They are the great intellectual achievements of the first half of the twentieth century. The general theory of relativity describes the force of gravity and the large-scale structure of the universe; that is, the structure on scales from only a few miles to as large as a million million million million (1 with twenty-four zeros after it) miles, the size of the observable universe. Quantum mechanics, on the other hand, deals with phenomena on extremely small scales, such as a millionth of a millionth of an inch. Unfortunately, however, these two theories are known to be inconsistent with each other—they cannot both be correct. One of the major endeavors in physics today, and the major theme of this book, is the search for a new theory that will incorporate them both —a quantum theory of gravity. We do not yet have such a theory, and we may still be a long way from having one, but we do already know many of the properties that it must have. And we shall see in later chapters that we already know a fair amount about the predictions a quantum theory of gravity must make.</p>

        <figure id="figure-4-atoms-to-galaxies">
        <img src="../images/atoms-to-galaxies.jpg" alt="atoms-to-galaxies" />
        <figcaption>Atoms to Galaxies — In the first half of the twentieth century, physicists extended the reach of their theories from the everyday world of Isaac Newton to both the smallest and the largest extremes of our universe.</figcaption>
        </figure>

        <p>Now, if you believe that the universe is not arbitrary but is governed by definite laws, you ultimately have to combine the partial theories into a complete unified theory that will describe everything in the universe. But there is a fundamental paradox in the search for such a complete unified theory. The ideas about scientific theories outlined above assume we are rational beings who are free to observe the universe as we want and to draw logical deductions from what we see. In such a scheme it is reasonable to suppose that we might progress ever closer toward the laws that govern our universe. Yet if there really were a complete unified theory, it would also presumably determine our actions—so the theory itself would determine the outcome of our search for it! And why should it determine that we come to the right conclusions from the evidence? Might it not equally well determine that we draw the wrong conclusion? Or no conclusion at all?</p>


        <p>The only answer that we can give to this problem is based on Darwin’s principle of natural  selection. The idea is that in any population of self-reproducing organisms, there will be variations in  the genetic material and upbringing that different individuals have. These differences will mean that  some individuals are better able than others to draw the right conclusions about the world around  them and to act accordingly. These individuals will be more likely to survive and reproduce, so their  pattern of behavior and thought will come to dominate. It has certainly been true in the past that what  we call intelligence and scientific discovery have conveyed a survival advantage. It is not so clear  that this is still the case: our scientific discoveries may well destroy us all, and even if they don’t, a  complete unified theory may not make much difference to our chances of survival. However,  provided the universe has evolved in a regular way, we might expect that the reasoning abilities that  natural selection has given us would also be valid in our search for a complete unified theory and so  would not lead us to the wrong conclusions.</p>


        <p>Because the partial theories that we already have are sufficient to make accurate predictions in all  but the most extreme situations, the search for the ultimate theory of the universe seems difficult to  justify on practical grounds. (It is worth noting, though, that similar arguments could have been used  against both relativity and quantum mechanics, and these theories have given us both nuclear energy  and the microelectronics revolution.) The discovery of a complete unified theory, therefore, may not  aid the survival of our species. It may not even affect our lifestyle. But ever since the dawn of  civilization, people have not been content to see events as unconnected and inexplicable. We have  craved an understanding of the underlying order in the world. Today we still yearn to know why we  are here and where we came from. Humanity’s deepest desire for knowledge is justification enough  for our continuing quest. And our goal is nothing less than a complete description of the universe we live in.

        </p>
      </section>
    </div>
  </div>
<?php include '../chapters/toc.php';?>
<?php include '../parts/footer.php';?>