<?php
// PHP Variables & metadata
$currentChapterTitle = 'Curved Space';
$currentChapterDescription = 'Einstein\'s theory of General Relativity is based on the revolutionary suggestion that gravity is not a force like other forces but a consequence of the fact that space-time is not flat, as had been previously assumed.';
$nextChapterTitle = 'The expanding Universe';
$nextChapterURL = '7';
?>

<?php include '../parts/header.php';?>

  <div class="six book">
    <div class="container">
      <section class="chapter">
        <h2 id="chapter-6">Curved Space</h2>
        <p>Einstein's theory of <a href="/glossary#general-relativity" class="one-digit footnote-marker" rel="footnote">General Relativity</a> is based on the revolutionary suggestion that gravity is not a force like other forces but a consequence of the fact that <a href="/glossary#space-time" class="footnote-marker" rel="footnote">space-time</a> is not flat, as had been previously assumed. In general relativity, space-time is curved, or "warped," by the distribution of <a href="/glossary#mass" class="one-digit footnote-marker" rel="footnote">mass</a> and energy in it. Bodies such as the earth are not made to move on curved orbits bv a force called gravity; instead they move in curved orbits because they follow the nearest thing to a straight path in a curved space, which is called a <a href="/glossary#geodesic" class="one-digit footnote-marker" rel="footnote">geodesic</a>. Technically speaking, a geodesic is defined as the shortest (or longest) path between two nearby points.</p>

        <p>A geometric plane is an example of a two-dimensional flat space, on which the geodesics are lines. The surface of the earth is a two-dimensional curved space. A geodesic on the earth is called a great circle. The equator is a great circle. So is any other circle on the globe whose center coincides with the center of the earth. (The term "great circle" comes from the fact that these are the largest circles you can draw on the globe.) As the geodesic is the shortest path between two airports, this is the route an airline navigator will tell the pilot to fly along. For instance, you could fly from New York to Madrid by following your compass for 3,707 miles almost straight east, along their common line of latitude. But you can get there in 3,605 miles if you fly along a great circle, heading first northeast, then gradually turning east, and then southeast. The appearance of these two paths on a map, in which the surface of the globe has been distorted (flattened out), is deceiving. When you move "straight" east, you are not really moving straight, at least not straight in the sense of the most direct path, the geodesic.</p>


        <figure id="figure-11-global-distances">
          <picture>
            <source type="image/webp"
                    srcset="../images/worlds-300.webp 300w,
                            ../images/worlds-600.webp 600w,
                            ../images/worlds-800.webp 800w,
                            ../images/worlds.webp 1000w"
                     />
            <source srcset="../images/worlds-300.jpg 300w,
                            ../images/worlds-600.jpg 600w,
                            ../images/worlds-800.jpg 800w,
                            ../images/worlds.jpg 1000w"
                    />
            <img src="../images/worlds-300.jpg"
            alt="The Speed of Light and the Timing of Eclipses" />
          </picture>
        <figcaption>Distances on the Globe - The shortest distance between two points on the globe is along a great circle, which does not correspond to a straight line if you are looking at a flat map</figcaption>
        </figure>



        <p> In general relativity, bodies always follow geodesics in four-dimensional space-time. In the absence of matter, these geodesics in four-dimensional space-time correspond to straight lines in threedimensional space. In the presence of matter, four-dimensional space-time is distorted, causing the paths of bodies in three-dimensional space to curve in a manner that in the old Newtonian theory was explained by the effects of gravitational attraction. This is rather like watching an airplane flying over hilly ground. The plane might be moving in a straight line through three-dimensional space, but remove the third dimension-height-and you find that its shadow follows a curved path on the hilly two-dimensional ground. Or imagine a spaceship flying in a straight line through space, passing directly over the North Pole. Project its path down onto the two-dimensional surface of the earth and you find that it follows a semicircle, tracing a line of longitude over the northern hemisphere. Though the phenomenon is harder to picture, the mass of the sun curves space-time in such a way that although the earth follows a straight path in four-dimensional space-time, it appears to us to move along a nearly circular orbit in three-dimensional space.</p>

        <figure id="figure-12-space-craft">
          <img src="../images/space-craft.jpg" alt="Path of a Spacecraft’s Shadow" />
        <figcaption>Path of a Spacecraft’s Shadow
        Projected onto the two-dimensional globe, the path of a spacecraft flying along a straight line in space
        will appear curved</figcaption>
        </figure>


        <p>Actually, although they are derived differently, the orbits of the planets predicted by general relativity are almost exactly the same as those predicted by the Newtonian theory of gravity. The largest deviation is in the orbit of Mercury, which, being the planet nearest to the sun, feels the strongest gravitational effects and has a rather elongated elliptical orbit. General relativity predicts that the long axis of the ellipse should rotate about the sun at a rate of about one degree per ten thousand years. Small though this effect is, it had been noticed (<a href="/chapters/3">see Chapter 3</a>) long before 1915, and it served as one of the first confirmations of Einstein’s theory. In recent years, the even smaller deviations of the orbits of the other planets from the Newtonian predictions have been measured by <a href="/glossary#radar" class="one-digit footnote-marker" rel="footnote">radar</a> and found to agree with the predictions of general relativity.
        </p>
        <p>Light rays too must follow geodesics in space-time. Again, the fact that space is curved means that light no longer appears to travel in straight lines in space, so general relativity predicts that gravitational fields should bend light. For example, the theory predicts that the path of light near the sun would be slightly bent inward, on account of the mass of the sun. This means that light from a distant star that happened to pass near the sun would be deflected through a small angle, causing the star to appear in a different position to an observer on the earth. Of course, if the light from the star always passed close to the sun, we would not be able to tell whether the light was being deflected or if instead the star was really where we seem to see it. However, as the earth orbits around the sun, different stars appear to pass behind the sun and have their light deflected. They therefore change their apparent position relative to the other stars.</p>

        <figure id="figure-13-mercury-orbit">
          <img src="../images/mercury-orbit.jpg" alt="Precession of Mercury’s Orbit" />
        <figcaption>Precession of Mercury’s Orbit - As Mercury repeatedly orbits the sun, the long axis of its elliptical path slowly rotates, coming full circle roughly every 360,000 years</figcaption>
        </figure>

        <figure id="figure-14-bending-light">
          <img src="../images/bending-light.jpg" alt="Bending of Light Near the Sun" />
        <figcaption>Bending of Light Near the Sun -  When the sun lies almost directly between the earth and a distant star, its gravitational field deflects the star’s light, altering its apparent position.</figcaption>
        </figure>


        <p>It is normally very difficult to see this effect, because the light from the sun makes it impossible to observe stars that appear near to the sun in the sky. However, it is possible to do so during an eclipse of the sun, when the moon blocks the sun’s light. Einstein’s prediction of light deflection could not be tested immediately in 1915, because the First World War was in progress. It was not until 1919 that a British expedition, observing an eclipse from the coast of West Africa, showed that light was indeed deflected by the sun, just as predicted by the theory. This proof of a German theory by British scientists was hailed as a great act of reconciliation between the two countries after the war. It is ironic, therefore, that later examination of the photographs taken on that expedition showed the errors were as great as the effect they were trying to measure. Their measurement had been sheer luck, or perhaps a case of knowing the result they wanted to get-not an uncommon occurrence in science. The light deflection has, however, been accurately confirmed by a number of later observations.</p>

        <p>Another prediction of general relativity is that time should appear to run slower near a massive body such as the earth. Einstein first realized this in 1907, five years before he realized that gravity also altered the shape of space, and eight years before he completed his theory. He derived the effect using his principle of equivalence, which played the role in general relativity that the fundamental postulate played in the special theory. Recall that the fundamental postulate of <a href="/glossary#special-relativity" class="footnote-marker" rel="footnote">special relativity</a> stated that the laws of science should be the same for all freely moving observers, no matter what speed they were moving at. Roughly speaking, the principle of equivalence extends this to those observers who are not freely moving but are under the influence of a gravitational field. In a precise statement of the principle there are some technical points, such as the fact that if the gravitational field is not uniform, you must apply the principle separately to a series of small, overlapping patches, but we won’t concern ourselves with that here. For our purposes, we can state the principle this way: in small enough regions of space, it is impossible to tell if you are at rest in a gravitational field or uniformly accelerating in empty space.</p>

        <p>Imagine that you are in an elevator in empty space. There is no gravity, no "up" and no "down." You are floating freely. Now the elevator starts to move with constant <a href="/glossary#acceleration" class="footnote-marker" rel="footnote">acceleration</a>. You suddenly feel weight. That is, you feel a pull toward one end of the elevator, which suddenly seems to you to be the floor! If you now hold out an apple and let go, it drops to the floor. In fact, now that you are accelerating, everything that happens inside the elevator will unfold exactly as it would if the elevator was not moving at all but at rest in a uniform gravitational field. Einstein realized that just as you cannot tell from inside a train whether or not you are moving uniformly, you also cannot tell from inside the elevator whether you are uniformly accelerating or in a uniform gravitational field. The result was his principle of equivalence.</p>

        <p>The principle of equivalence, and the above example of it, is true only if inertial mass (the mass in Newton’s second law that determines how much you accelerate in response to a force) and gravitational mass (the mass in Newton’s law of gravity that determines how much gravitational force you feel) are the same thing (<a href="/chapters/4">see Chapter 4</a>). That’s because if both kinds of mass are the same, then all objects in a gravitational field will fall at the same rate, no matter what their mass. If this equivalence weren’t true, then under the influence of gravity some objects would fall faster than others, which would mean you could distinguish the pull of gravity from uniform acceleration, in which everything does fall at the same rate. Einstein’s use of the equivalence of inertial and gravitational mass to derive his principle of equivalence, and eventually all of general relativity, amounts to a relentless march of logical reasoning unmatched in the history of human thought.</p>

        <p>Now that we know the principle of equivalence, we can start to follow Einstein’s logic by doing another thought experiment that shows why time must be affected by gravity. Imagine a rocket ship out in space. For convenience, imagine that the rocket ship is so long that light takes one second to traverse it from top to bottom. Finally, suppose there is an observer at the ceiling of the rocket ship and another at the floor, each with identical clocks that tick once each second.</p>

        <p>Suppose the ceiling observer w aits for the clock to tick, and then immediately sends a light signal down to the floor observer. The ceiling observer does this once more the next time the clock ticks. According to this setup, each signal travels for one second and then is received by the floor observer. So just as the ceiling observer sends two light signals a second apart, the floor observer receives two, one second apart.</p>

        <p>How would this situation differ if the rocket ship were resting on earth, under the influence of gravity, instead of floating freely out in space? According to Newton’s theory, gravity has no effect on this situation. If the observer on the ceiling sends signals one second apart, the observer will receive them one second apart. But the principle of equivalence does not make the same prediction. We can see what happens, that principle tells us, by considering the effect of uniform acceleration instead of the effect of gravity. This is an example of the way Einstein used the principle of equivalence to create his new theory of gravity.</p>

        <p>So let’s now suppose the rocket ship is accelerating. (We will imagine that it is accelerating slowly, so we don’t approach the speed of light!) Since the rocket ship is moving upward, the first signal will have less distance to travel than before and so will arrive sooner than one second later. If the rocket ship were moving at a constant speed, the second signal would arrive exactly the same amount of time sooner, so the time between the two signals would remain one second. But due to the acceleration, the rocket ship will be moving even faster when the second signal is sent than it was when the first signal was sent, so the second signal will have even less distance to traverse than the first and will arrive in even less time. The observer on the floor will therefore measure less than one second between the signals, disagreeing with the ceiling observer, who claims to have sent them exactly one second apart.</p>

        <p>This is probably not startling in the case of the accelerating rocket ship—after all, we just explained it! But remember, the principle of equivalence says that it also applies to a rocket ship at rest in a gravitational field. That means that even if the rocket ship is not accelerating but, say, is sitting on a launching pad on the earth’s surface, if the ceiling observer sends signals toward the floor at intervals of one each second (according to his clock), the floor observer will receive the signals at shorter intervals (according to his clock). That is startling!</p>

        <p>You might still ask whether this means that gravity changes time, or whether it merely ruins clocks. Suppose the floor observer climbs up to the ceiling, where he and his partner compare their clocks. They are identical clocks, and sure enough, both observers will find that they now agree on the length of a second. There is nothing wrong with the floor observer’s clock: it measures the local flow of time, wherever it happens to be. So just as special relativity tells us that time runs differently for observers in relative motion, general relativity tells us that time runs differently for observers at different heights in a gravitational field. According to general relativity, the floor observer measured less than one second between signals because time moves more slowly closer to the earth’s surface. The stronger the field, the greater this effect. Newton’s laws of motion put an end to the idea of absolute position in space. We have now seen how the theory of relativity gets rid of absolute time.</p>

        <p>This prediction was tested in 1962, using a pair of very accurate clocks mounted at the top and bottom of a water tower. The clock at the bottom, which was nearer the earth, was found to run slower, in exact agreement with general relativity. The effect is a small one-a clock on the surface of the sun would gain only about a minute a year as compared to one on the surface of the earth. Yet with the advent of very accurate navigation systems based on signals from satellites, the difference in the speed of clocks at different heights above the earth is now of considerable practical importance. If you ignored the predictions of general relativity, the position that you calculated would be wrong by several miles!</p>

        <p>Our biological clocks are equally affected by these changes in the flow of time. Consider a pair of twins. Suppose that one twin goes to live on the top of a mountain while the other stays at sea level. The first twin would age faster than the second. Thus, if the; met again, one would be older than the other. In this case, the difference in ages would be very small, but it would be much larger if one of the twins went for a long trip in a spaceship in which he accelerated to nearly the speed of light. When he returned, he would be much younger than the one who stayed on earth. This is known as the twins paradox, but it is a paradox only if you have the idea of absolute time at the back of your mind. In the theory of relativity there is no unique absolute time; instead, each individual has his own personal measure of time that depends on where he is and how he is moving.</p>

        <p>Before 1915, space and time were thought of as a fixed arena in which events took place but which was not affected by what happened in it. This was true even of the special theory of relativity. Bodies moved, forces attracted and repelled, but time and space simply continued unaffected. It was natural to think that space and time went on forever. The situation, however, is quite different in the general theory of relativity. Space and time are now dynamic quantities: when a body moves or a force acts, it affects the curvature of space and time—and in turn the structure of space-time affects the way in which bodies move and forces act. Space and time not only affect but also are affected by everything that happens in the univ erse. Just as we cannot talk about events in the universe without the notions of space and time, so in general relativity it became meaningless to talk about space and time outside the limits of the universe. In the decades following 1915, this new understanding of space and time was to revolutionize our view of the universe. As we will see, the old idea of an essentially unchanging universe that could have existed forever, and could continue to exist forever, was replaced by the notion of a dynamic, expanding universe that seemed to have begun a finite time ago and which might end at a finite time in the future.</p>
      </section>
    </div>
  </div>
<?php include '../chapters/toc.php';?>
<?php include '../parts/footer.php';?>